
spring.datasource.url=jdbc:postgresql://localhost:5432/lojinha_bairro
spring.datasource.username=postgres
spring.datasource.password=admin

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.driver-class-name=org.postgresql.Driver

server.port=8087

cloudinary.cloud_name=${CLOUDINARY_CLOUD_NAME:seu_cloud_name_local}
cloudinary.api_key=${CLOUDINARY_API_KEY:sua_key_local}
cloudinary.api_secret=${CLOUDINARY_API_SECRET:sua_secret_local}

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


server.address=0.0.0.0
spring.web.resources.static-locations=classpath:/static/