
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/lojinha_bairro}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASS:admin}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


server.port=${PORT:8080}


cloudinary.cloud_name=${CLOUDINARY_CLOUD_NAME:seu_cloud_name_local}
cloudinary.api_key=${CLOUDINARY_API_KEY:sua_key_local}
cloudinary.api_secret=${CLOUDINARY_API_SECRET:sua_secret_local}